version: "2"

services:
  mysql-container:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./resources/mysql:/docker-entrypoint-initdb.d
